openapi: "3.0.3"
info:
  title: "delivery_fee_calculator_backend_kotlin API"
  description: "delivery_fee_calculator_backend_kotlin API"
  version: "1.0.0"
servers:
- url: "https://delivery_fee_calculator_backend_kotlin"
paths:
  /deliveryFee:
    post:
      description: ""
      requestBody:
        content:
          '*/*':
            schema:
              $ref: "#/components/schemas/DeliveryFeeRequest"
        required: true
      responses:
        "200":
          description: "OK <br> Send response"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/DeliveryFeeResponse"
components:
  schemas:
    DeliveryFeeRequest:
      type: "object"
      properties:
        cart_value:
          type: "integer"
          format: "int32"
        delivery_distance:
          type: "integer"
          format: "int32"
        number_of_items:
          type: "integer"
          format: "int32"
        time:
          type: "string"
          format: "date-time"
      required:
      - "time"
    DeliveryFeeResponse:
      type: "object"
      properties:
        delivery_fee:
          type: "integer"
          format: "int32"